// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsMessages(lhsKey, rhsKey) {
          if deepEqualsMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Predefined error types for consistent error handling across platforms
enum PasskeyErrorType: Int {
  case invalidParameters = 0
  case missingRequiredField = 1
  case invalidFormat = 2
  case decodingChallenge = 3
  case userCancelled = 4
  case userTimeout = 5
  case userOptedOut = 6
  case insufficientPermissions = 7
  case securityViolation = 8
  case notAllowed = 9
  case domainNotAssociated = 10
  case noCredentialsAvailable = 11
  case credentialNotFound = 12
  case invalidCredential = 13
  case credentialAlreadyExists = 14
  case invalidResponse = 15
  case notHandled = 16
  case failed = 17
  case platformNotSupported = 18
  case operationNotSupported = 19
  case systemError = 20
  case networkError = 21
  case domError = 22
  case webauthnError = 23
  case attestationError = 24
  case excludeCredentialsMatch = 25
  case unexpectedAuthorizationResponse = 26
  case wkErrorDomain = 27
  case unknownError = 28
  case unexpectedError = 29
}

/// Represents a standardized passkey exception that can be thrown across platforms
///
/// Generated class from Pigeon that represents data sent in messages.
struct PasskeyException: Hashable {
  /// Error type identifying the specific type of error
  var errorType: PasskeyErrorType
  /// Error message describing what went wrong
  var message: String
  /// Optional additional details about the error
  var details: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PasskeyException? {
    let errorType = pigeonVar_list[0] as! PasskeyErrorType
    let message = pigeonVar_list[1] as! String
    let details = pigeonVar_list[2] as! String

    return PasskeyException(
      errorType: errorType,
      message: message,
      details: details
    )
  }
  func toList() -> [Any?] {
    return [
      errorType,
      message,
      details,
    ]
  }
  static func == (lhs: PasskeyException, rhs: PasskeyException) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.errorType, rhs.errorType) && deepEqualsMessages(lhs.message, rhs.message) && deepEqualsMessages(lhs.details, rhs.details)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PasskeyException")
    deepHashMessages(value: errorType, hasher: &hasher)
    deepHashMessages(value: message, hasher: &hasher)
    deepHashMessages(value: details, hasher: &hasher)
  }
}

/// Represents the response data for authentication generation options
///
/// Generated class from Pigeon that represents data sent in messages.
struct AuthGenerateOptionResponseData: Hashable {
  /// The relying party identifier
  var rpId: String
  /// The challenge string
  var challenge: String
  /// List of allowed credentials
  var allowCredentials: [AuthGenerateOptionAllowCredential]
  /// Timeout value in milliseconds
  var timeout: Int64
  /// User verification requirement
  var userVerification: String
  /// Hints for the authenticator
  var hints: [String?]? = nil
  /// Extensions for authentication
  var extensions: AuthGenerateOptionExtension? = nil
  /// Prefer credentials immediately available on-device (no QR/remote prompts)
  var preferImmediatelyAvailableCredentials: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AuthGenerateOptionResponseData? {
    let rpId = pigeonVar_list[0] as! String
    let challenge = pigeonVar_list[1] as! String
    let allowCredentials = pigeonVar_list[2] as! [AuthGenerateOptionAllowCredential]
    let timeout = pigeonVar_list[3] as! Int64
    let userVerification = pigeonVar_list[4] as! String
    let hints: [String?]? = nilOrValue(pigeonVar_list[5])
    let extensions: AuthGenerateOptionExtension? = nilOrValue(pigeonVar_list[6])
    let preferImmediatelyAvailableCredentials: Bool? = nilOrValue(pigeonVar_list[7])

    return AuthGenerateOptionResponseData(
      rpId: rpId,
      challenge: challenge,
      allowCredentials: allowCredentials,
      timeout: timeout,
      userVerification: userVerification,
      hints: hints,
      extensions: extensions,
      preferImmediatelyAvailableCredentials: preferImmediatelyAvailableCredentials
    )
  }
  func toList() -> [Any?] {
    return [
      rpId,
      challenge,
      allowCredentials,
      timeout,
      userVerification,
      hints,
      extensions,
      preferImmediatelyAvailableCredentials,
    ]
  }
  static func == (lhs: AuthGenerateOptionResponseData, rhs: AuthGenerateOptionResponseData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.rpId, rhs.rpId) && deepEqualsMessages(lhs.challenge, rhs.challenge) && deepEqualsMessages(lhs.allowCredentials, rhs.allowCredentials) && deepEqualsMessages(lhs.timeout, rhs.timeout) && deepEqualsMessages(lhs.userVerification, rhs.userVerification) && deepEqualsMessages(lhs.hints, rhs.hints) && deepEqualsMessages(lhs.extensions, rhs.extensions) && deepEqualsMessages(lhs.preferImmediatelyAvailableCredentials, rhs.preferImmediatelyAvailableCredentials)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AuthGenerateOptionResponseData")
    deepHashMessages(value: rpId, hasher: &hasher)
    deepHashMessages(value: challenge, hasher: &hasher)
    deepHashMessages(value: allowCredentials, hasher: &hasher)
    deepHashMessages(value: timeout, hasher: &hasher)
    deepHashMessages(value: userVerification, hasher: &hasher)
    deepHashMessages(value: hints, hasher: &hasher)
    deepHashMessages(value: extensions, hasher: &hasher)
    deepHashMessages(value: preferImmediatelyAvailableCredentials, hasher: &hasher)
  }
}

/// Represents extensions for authentication options
///
/// Generated class from Pigeon that represents data sent in messages.
struct AuthGenerateOptionExtension: Hashable {
  /// AppID extension
  var appid: Bool? = nil
  /// PRF extension input parameters
  var prf: PrfExtensionInput? = nil
  /// LargeBlob extension input for authentication
  var largeBlob: LargeBlobExtensionAuthInput? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AuthGenerateOptionExtension? {
    let appid: Bool? = nilOrValue(pigeonVar_list[0])
    let prf: PrfExtensionInput? = nilOrValue(pigeonVar_list[1])
    let largeBlob: LargeBlobExtensionAuthInput? = nilOrValue(pigeonVar_list[2])

    return AuthGenerateOptionExtension(
      appid: appid,
      prf: prf,
      largeBlob: largeBlob
    )
  }
  func toList() -> [Any?] {
    return [
      appid,
      prf,
      largeBlob,
    ]
  }
  static func == (lhs: AuthGenerateOptionExtension, rhs: AuthGenerateOptionExtension) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.appid, rhs.appid) && deepEqualsMessages(lhs.prf, rhs.prf) && deepEqualsMessages(lhs.largeBlob, rhs.largeBlob)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AuthGenerateOptionExtension")
    deepHashMessages(value: appid, hasher: &hasher)
    deepHashMessages(value: prf, hasher: &hasher)
    deepHashMessages(value: largeBlob, hasher: &hasher)
  }
}

/// Represents an allowed credential for authentication
///
/// Generated class from Pigeon that represents data sent in messages.
struct AuthGenerateOptionAllowCredential: Hashable {
  /// The credential identifier
  var id: String
  /// The credential type
  var type: String
  /// List of transport methods
  var transports: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AuthGenerateOptionAllowCredential? {
    let id = pigeonVar_list[0] as! String
    let type = pigeonVar_list[1] as! String
    let transports = pigeonVar_list[2] as! [String]

    return AuthGenerateOptionAllowCredential(
      id: id,
      type: type,
      transports: transports
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      type,
      transports,
    ]
  }
  static func == (lhs: AuthGenerateOptionAllowCredential, rhs: AuthGenerateOptionAllowCredential) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.id, rhs.id) && deepEqualsMessages(lhs.type, rhs.type) && deepEqualsMessages(lhs.transports, rhs.transports)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AuthGenerateOptionAllowCredential")
    deepHashMessages(value: id, hasher: &hasher)
    deepHashMessages(value: type, hasher: &hasher)
    deepHashMessages(value: transports, hasher: &hasher)
  }
}

/// Represents the response data for authentication verification
///
/// Generated class from Pigeon that represents data sent in messages.
struct AuthVerifyResponse: Hashable {
  /// Whether the authentication was verified
  var verified: Bool
  /// Access token for authenticated session
  var accessToken: String
  /// User information (optional)
  var user: User? = nil
  /// Refresh token for session renewal
  var refreshToken: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AuthVerifyResponse? {
    let verified = pigeonVar_list[0] as! Bool
    let accessToken = pigeonVar_list[1] as! String
    let user: User? = nilOrValue(pigeonVar_list[2])
    let refreshToken = pigeonVar_list[3] as! String

    return AuthVerifyResponse(
      verified: verified,
      accessToken: accessToken,
      user: user,
      refreshToken: refreshToken
    )
  }
  func toList() -> [Any?] {
    return [
      verified,
      accessToken,
      user,
      refreshToken,
    ]
  }
  static func == (lhs: AuthVerifyResponse, rhs: AuthVerifyResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.verified, rhs.verified) && deepEqualsMessages(lhs.accessToken, rhs.accessToken) && deepEqualsMessages(lhs.user, rhs.user) && deepEqualsMessages(lhs.refreshToken, rhs.refreshToken)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AuthVerifyResponse")
    deepHashMessages(value: verified, hasher: &hasher)
    deepHashMessages(value: accessToken, hasher: &hasher)
    deepHashMessages(value: user, hasher: &hasher)
    deepHashMessages(value: refreshToken, hasher: &hasher)
  }
}

/// Represents user information
///
/// Generated class from Pigeon that represents data sent in messages.
struct User: Hashable {
  /// User identifier
  var id: String
  /// Username
  var username: String
  /// Phone number (optional)
  var phone: String? = nil
  /// Email address (optional)
  var email: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> User? {
    let id = pigeonVar_list[0] as! String
    let username = pigeonVar_list[1] as! String
    let phone: String? = nilOrValue(pigeonVar_list[2])
    let email: String? = nilOrValue(pigeonVar_list[3])

    return User(
      id: id,
      username: username,
      phone: phone,
      email: email
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      username,
      phone,
      email,
    ]
  }
  static func == (lhs: User, rhs: User) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.id, rhs.id) && deepEqualsMessages(lhs.username, rhs.username) && deepEqualsMessages(lhs.phone, rhs.phone) && deepEqualsMessages(lhs.email, rhs.email)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("User")
    deepHashMessages(value: id, hasher: &hasher)
    deepHashMessages(value: username, hasher: &hasher)
    deepHashMessages(value: phone, hasher: &hasher)
    deepHashMessages(value: email, hasher: &hasher)
  }
}

/// Represents the response data for creating a passkey
///
/// Generated class from Pigeon that represents data sent in messages.
struct CreatePasskeyResponseData: Hashable {
  /// Raw identifier
  var rawId: String
  /// Authenticator attachment type
  var authenticatorAttachment: String? = nil
  /// Type of credential
  var type: String
  /// Credential identifier
  var id: String
  /// Response data from passkey creation
  var response: CreatePasskeyResponse
  /// Client extension results
  var clientExtensionResults: CreatePasskeyExtension
  /// Username associated with the passkey
  var username: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CreatePasskeyResponseData? {
    let rawId = pigeonVar_list[0] as! String
    let authenticatorAttachment: String? = nilOrValue(pigeonVar_list[1])
    let type = pigeonVar_list[2] as! String
    let id = pigeonVar_list[3] as! String
    let response = pigeonVar_list[4] as! CreatePasskeyResponse
    let clientExtensionResults = pigeonVar_list[5] as! CreatePasskeyExtension
    let username = pigeonVar_list[6] as! String

    return CreatePasskeyResponseData(
      rawId: rawId,
      authenticatorAttachment: authenticatorAttachment,
      type: type,
      id: id,
      response: response,
      clientExtensionResults: clientExtensionResults,
      username: username
    )
  }
  func toList() -> [Any?] {
    return [
      rawId,
      authenticatorAttachment,
      type,
      id,
      response,
      clientExtensionResults,
      username,
    ]
  }
  static func == (lhs: CreatePasskeyResponseData, rhs: CreatePasskeyResponseData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.rawId, rhs.rawId) && deepEqualsMessages(lhs.authenticatorAttachment, rhs.authenticatorAttachment) && deepEqualsMessages(lhs.type, rhs.type) && deepEqualsMessages(lhs.id, rhs.id) && deepEqualsMessages(lhs.response, rhs.response) && deepEqualsMessages(lhs.clientExtensionResults, rhs.clientExtensionResults) && deepEqualsMessages(lhs.username, rhs.username)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CreatePasskeyResponseData")
    deepHashMessages(value: rawId, hasher: &hasher)
    deepHashMessages(value: authenticatorAttachment, hasher: &hasher)
    deepHashMessages(value: type, hasher: &hasher)
    deepHashMessages(value: id, hasher: &hasher)
    deepHashMessages(value: response, hasher: &hasher)
    deepHashMessages(value: clientExtensionResults, hasher: &hasher)
    deepHashMessages(value: username, hasher: &hasher)
  }
}

/// Represents the response from passkey creation
///
/// Generated class from Pigeon that represents data sent in messages.
struct CreatePasskeyResponse: Hashable {
  /// Client data JSON
  var clientDataJSON: String
  /// Attestation object
  var attestationObject: String
  /// List of transport methods
  var transports: [String?]? = nil
  /// Authenticator data
  var authenticatorData: String? = nil
  /// Public key algorithm identifier
  var publicKeyAlgorithm: Int64? = nil
  /// Public key
  var publicKey: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CreatePasskeyResponse? {
    let clientDataJSON = pigeonVar_list[0] as! String
    let attestationObject = pigeonVar_list[1] as! String
    let transports: [String?]? = nilOrValue(pigeonVar_list[2])
    let authenticatorData: String? = nilOrValue(pigeonVar_list[3])
    let publicKeyAlgorithm: Int64? = nilOrValue(pigeonVar_list[4])
    let publicKey: String? = nilOrValue(pigeonVar_list[5])

    return CreatePasskeyResponse(
      clientDataJSON: clientDataJSON,
      attestationObject: attestationObject,
      transports: transports,
      authenticatorData: authenticatorData,
      publicKeyAlgorithm: publicKeyAlgorithm,
      publicKey: publicKey
    )
  }
  func toList() -> [Any?] {
    return [
      clientDataJSON,
      attestationObject,
      transports,
      authenticatorData,
      publicKeyAlgorithm,
      publicKey,
    ]
  }
  static func == (lhs: CreatePasskeyResponse, rhs: CreatePasskeyResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.clientDataJSON, rhs.clientDataJSON) && deepEqualsMessages(lhs.attestationObject, rhs.attestationObject) && deepEqualsMessages(lhs.transports, rhs.transports) && deepEqualsMessages(lhs.authenticatorData, rhs.authenticatorData) && deepEqualsMessages(lhs.publicKeyAlgorithm, rhs.publicKeyAlgorithm) && deepEqualsMessages(lhs.publicKey, rhs.publicKey)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CreatePasskeyResponse")
    deepHashMessages(value: clientDataJSON, hasher: &hasher)
    deepHashMessages(value: attestationObject, hasher: &hasher)
    deepHashMessages(value: transports, hasher: &hasher)
    deepHashMessages(value: authenticatorData, hasher: &hasher)
    deepHashMessages(value: publicKeyAlgorithm, hasher: &hasher)
    deepHashMessages(value: publicKey, hasher: &hasher)
  }
}

/// Represents client extension results for passkey creation
///
/// Generated class from Pigeon that represents data sent in messages.
struct CreatePasskeyExtension: Hashable {
  /// Credential properties extension (optional)
  var credProps: CreatePasskeyExtensionProps? = nil
  /// PRF extension (optional)
  var prf: PrfExtensionOutput? = nil
  /// LargeBlob extension output for registration
  var largeBlob: LargeBlobExtensionRegistrationOutput? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CreatePasskeyExtension? {
    let credProps: CreatePasskeyExtensionProps? = nilOrValue(pigeonVar_list[0])
    let prf: PrfExtensionOutput? = nilOrValue(pigeonVar_list[1])
    let largeBlob: LargeBlobExtensionRegistrationOutput? = nilOrValue(pigeonVar_list[2])

    return CreatePasskeyExtension(
      credProps: credProps,
      prf: prf,
      largeBlob: largeBlob
    )
  }
  func toList() -> [Any?] {
    return [
      credProps,
      prf,
      largeBlob,
    ]
  }
  static func == (lhs: CreatePasskeyExtension, rhs: CreatePasskeyExtension) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.credProps, rhs.credProps) && deepEqualsMessages(lhs.prf, rhs.prf) && deepEqualsMessages(lhs.largeBlob, rhs.largeBlob)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CreatePasskeyExtension")
    deepHashMessages(value: credProps, hasher: &hasher)
    deepHashMessages(value: prf, hasher: &hasher)
    deepHashMessages(value: largeBlob, hasher: &hasher)
  }
}

/// Represents credential properties extension
///
/// Generated class from Pigeon that represents data sent in messages.
struct CreatePasskeyExtensionProps: Hashable {
  /// Resident key flag
  var rk: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CreatePasskeyExtensionProps? {
    let rk = pigeonVar_list[0] as! Bool

    return CreatePasskeyExtensionProps(
      rk: rk
    )
  }
  func toList() -> [Any?] {
    return [
      rk
    ]
  }
  static func == (lhs: CreatePasskeyExtensionProps, rhs: CreatePasskeyExtensionProps) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.rk, rhs.rk)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CreatePasskeyExtensionProps")
    deepHashMessages(value: rk, hasher: &hasher)
  }
}

/// Represents the response data for passkey authentication
///
/// Generated class from Pigeon that represents data sent in messages.
struct GetPasskeyAuthenticationResponseData: Hashable {
  /// Authenticator attachment type
  var authenticatorAttachment: String? = nil
  /// Credential identifier
  var id: String
  /// Raw identifier
  var rawId: String
  /// Authentication response data
  var response: GetPasskeyAuthenticationResponse
  /// Type of credential
  var type: String
  /// Client extension results
  var clientExtensionResults: AuthPasskeyExtensionResult? = nil
  /// Username associated with the passkey
  var username: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GetPasskeyAuthenticationResponseData? {
    let authenticatorAttachment: String? = nilOrValue(pigeonVar_list[0])
    let id = pigeonVar_list[1] as! String
    let rawId = pigeonVar_list[2] as! String
    let response = pigeonVar_list[3] as! GetPasskeyAuthenticationResponse
    let type = pigeonVar_list[4] as! String
    let clientExtensionResults: AuthPasskeyExtensionResult? = nilOrValue(pigeonVar_list[5])
    let username = pigeonVar_list[6] as! String

    return GetPasskeyAuthenticationResponseData(
      authenticatorAttachment: authenticatorAttachment,
      id: id,
      rawId: rawId,
      response: response,
      type: type,
      clientExtensionResults: clientExtensionResults,
      username: username
    )
  }
  func toList() -> [Any?] {
    return [
      authenticatorAttachment,
      id,
      rawId,
      response,
      type,
      clientExtensionResults,
      username,
    ]
  }
  static func == (lhs: GetPasskeyAuthenticationResponseData, rhs: GetPasskeyAuthenticationResponseData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.authenticatorAttachment, rhs.authenticatorAttachment) && deepEqualsMessages(lhs.id, rhs.id) && deepEqualsMessages(lhs.rawId, rhs.rawId) && deepEqualsMessages(lhs.response, rhs.response) && deepEqualsMessages(lhs.type, rhs.type) && deepEqualsMessages(lhs.clientExtensionResults, rhs.clientExtensionResults) && deepEqualsMessages(lhs.username, rhs.username)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GetPasskeyAuthenticationResponseData")
    deepHashMessages(value: authenticatorAttachment, hasher: &hasher)
    deepHashMessages(value: id, hasher: &hasher)
    deepHashMessages(value: rawId, hasher: &hasher)
    deepHashMessages(value: response, hasher: &hasher)
    deepHashMessages(value: type, hasher: &hasher)
    deepHashMessages(value: clientExtensionResults, hasher: &hasher)
    deepHashMessages(value: username, hasher: &hasher)
  }
}

/// Represents client extension results for passkey authentication
///
/// Generated class from Pigeon that represents data sent in messages.
struct AuthPasskeyExtensionResult: Hashable {
  /// AppID extension result
  var appid: Bool? = nil
  /// PRF extension output results
  var prf: PrfExtensionOutput? = nil
  /// LargeBlob extension output for authentication
  var largeBlob: LargeBlobExtensionAuthOutput? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AuthPasskeyExtensionResult? {
    let appid: Bool? = nilOrValue(pigeonVar_list[0])
    let prf: PrfExtensionOutput? = nilOrValue(pigeonVar_list[1])
    let largeBlob: LargeBlobExtensionAuthOutput? = nilOrValue(pigeonVar_list[2])

    return AuthPasskeyExtensionResult(
      appid: appid,
      prf: prf,
      largeBlob: largeBlob
    )
  }
  func toList() -> [Any?] {
    return [
      appid,
      prf,
      largeBlob,
    ]
  }
  static func == (lhs: AuthPasskeyExtensionResult, rhs: AuthPasskeyExtensionResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.appid, rhs.appid) && deepEqualsMessages(lhs.prf, rhs.prf) && deepEqualsMessages(lhs.largeBlob, rhs.largeBlob)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AuthPasskeyExtensionResult")
    deepHashMessages(value: appid, hasher: &hasher)
    deepHashMessages(value: prf, hasher: &hasher)
    deepHashMessages(value: largeBlob, hasher: &hasher)
  }
}

/// Represents the authentication response from passkey
///
/// Generated class from Pigeon that represents data sent in messages.
struct GetPasskeyAuthenticationResponse: Hashable {
  /// Client data JSON
  var clientDataJSON: String
  /// Authenticator data
  var authenticatorData: String
  /// Digital signature
  var signature: String
  /// User handle (optional)
  var userHandle: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GetPasskeyAuthenticationResponse? {
    let clientDataJSON = pigeonVar_list[0] as! String
    let authenticatorData = pigeonVar_list[1] as! String
    let signature = pigeonVar_list[2] as! String
    let userHandle: String? = nilOrValue(pigeonVar_list[3])

    return GetPasskeyAuthenticationResponse(
      clientDataJSON: clientDataJSON,
      authenticatorData: authenticatorData,
      signature: signature,
      userHandle: userHandle
    )
  }
  func toList() -> [Any?] {
    return [
      clientDataJSON,
      authenticatorData,
      signature,
      userHandle,
    ]
  }
  static func == (lhs: GetPasskeyAuthenticationResponse, rhs: GetPasskeyAuthenticationResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.clientDataJSON, rhs.clientDataJSON) && deepEqualsMessages(lhs.authenticatorData, rhs.authenticatorData) && deepEqualsMessages(lhs.signature, rhs.signature) && deepEqualsMessages(lhs.userHandle, rhs.userHandle)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GetPasskeyAuthenticationResponse")
    deepHashMessages(value: clientDataJSON, hasher: &hasher)
    deepHashMessages(value: authenticatorData, hasher: &hasher)
    deepHashMessages(value: signature, hasher: &hasher)
    deepHashMessages(value: userHandle, hasher: &hasher)
  }
}

/// Represents the data for generating registration options
///
/// Generated class from Pigeon that represents data sent in messages.
struct RegisterGenerateOptionData: Hashable {
  /// Challenge string
  var challenge: String
  /// Relying party information
  var rp: RegisterGenerateOptionRp
  /// User information
  var user: RegisterGenerateOptionUser
  /// Public key credential parameters
  var pubKeyCredParams: [RegisterGenerateOptionPublicKeyParams]
  /// Timeout value in milliseconds
  var timeout: Int64
  /// Attestation preference
  var attestation: String
  /// Credentials to exclude from registration
  var excludeCredentials: [RegisterGenerateOptionExcludeCredential]
  /// Authenticator selection criteria
  var authenticatorSelection: RegisterGenerateOptionAuthenticatorSelection
  /// Extensions for registration
  var extensions: RegisterGenerateOptionExtension
  /// Hints for the authenticator
  var hints: [String?]? = nil
  /// Attestation formats
  var attestationFormats: [String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegisterGenerateOptionData? {
    let challenge = pigeonVar_list[0] as! String
    let rp = pigeonVar_list[1] as! RegisterGenerateOptionRp
    let user = pigeonVar_list[2] as! RegisterGenerateOptionUser
    let pubKeyCredParams = pigeonVar_list[3] as! [RegisterGenerateOptionPublicKeyParams]
    let timeout = pigeonVar_list[4] as! Int64
    let attestation = pigeonVar_list[5] as! String
    let excludeCredentials = pigeonVar_list[6] as! [RegisterGenerateOptionExcludeCredential]
    let authenticatorSelection = pigeonVar_list[7] as! RegisterGenerateOptionAuthenticatorSelection
    let extensions = pigeonVar_list[8] as! RegisterGenerateOptionExtension
    let hints: [String?]? = nilOrValue(pigeonVar_list[9])
    let attestationFormats: [String?]? = nilOrValue(pigeonVar_list[10])

    return RegisterGenerateOptionData(
      challenge: challenge,
      rp: rp,
      user: user,
      pubKeyCredParams: pubKeyCredParams,
      timeout: timeout,
      attestation: attestation,
      excludeCredentials: excludeCredentials,
      authenticatorSelection: authenticatorSelection,
      extensions: extensions,
      hints: hints,
      attestationFormats: attestationFormats
    )
  }
  func toList() -> [Any?] {
    return [
      challenge,
      rp,
      user,
      pubKeyCredParams,
      timeout,
      attestation,
      excludeCredentials,
      authenticatorSelection,
      extensions,
      hints,
      attestationFormats,
    ]
  }
  static func == (lhs: RegisterGenerateOptionData, rhs: RegisterGenerateOptionData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.challenge, rhs.challenge) && deepEqualsMessages(lhs.rp, rhs.rp) && deepEqualsMessages(lhs.user, rhs.user) && deepEqualsMessages(lhs.pubKeyCredParams, rhs.pubKeyCredParams) && deepEqualsMessages(lhs.timeout, rhs.timeout) && deepEqualsMessages(lhs.attestation, rhs.attestation) && deepEqualsMessages(lhs.excludeCredentials, rhs.excludeCredentials) && deepEqualsMessages(lhs.authenticatorSelection, rhs.authenticatorSelection) && deepEqualsMessages(lhs.extensions, rhs.extensions) && deepEqualsMessages(lhs.hints, rhs.hints) && deepEqualsMessages(lhs.attestationFormats, rhs.attestationFormats)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RegisterGenerateOptionData")
    deepHashMessages(value: challenge, hasher: &hasher)
    deepHashMessages(value: rp, hasher: &hasher)
    deepHashMessages(value: user, hasher: &hasher)
    deepHashMessages(value: pubKeyCredParams, hasher: &hasher)
    deepHashMessages(value: timeout, hasher: &hasher)
    deepHashMessages(value: attestation, hasher: &hasher)
    deepHashMessages(value: excludeCredentials, hasher: &hasher)
    deepHashMessages(value: authenticatorSelection, hasher: &hasher)
    deepHashMessages(value: extensions, hasher: &hasher)
    deepHashMessages(value: hints, hasher: &hasher)
    deepHashMessages(value: attestationFormats, hasher: &hasher)
  }
}

/// Represents a credential to exclude from registration
///
/// Generated class from Pigeon that represents data sent in messages.
struct RegisterGenerateOptionExcludeCredential: Hashable {
  /// Credential identifier
  var id: String
  /// Credential type
  var type: String
  /// List of transport methods
  var transports: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegisterGenerateOptionExcludeCredential? {
    let id = pigeonVar_list[0] as! String
    let type = pigeonVar_list[1] as! String
    let transports = pigeonVar_list[2] as! [String]

    return RegisterGenerateOptionExcludeCredential(
      id: id,
      type: type,
      transports: transports
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      type,
      transports,
    ]
  }
  static func == (lhs: RegisterGenerateOptionExcludeCredential, rhs: RegisterGenerateOptionExcludeCredential) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.id, rhs.id) && deepEqualsMessages(lhs.type, rhs.type) && deepEqualsMessages(lhs.transports, rhs.transports)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RegisterGenerateOptionExcludeCredential")
    deepHashMessages(value: id, hasher: &hasher)
    deepHashMessages(value: type, hasher: &hasher)
    deepHashMessages(value: transports, hasher: &hasher)
  }
}

/// Represents relying party information for registration
///
/// Generated class from Pigeon that represents data sent in messages.
struct RegisterGenerateOptionRp: Hashable {
  /// Relying party name
  var name: String
  /// Relying party identifier
  var id: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegisterGenerateOptionRp? {
    let name = pigeonVar_list[0] as! String
    let id = pigeonVar_list[1] as! String

    return RegisterGenerateOptionRp(
      name: name,
      id: id
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      id,
    ]
  }
  static func == (lhs: RegisterGenerateOptionRp, rhs: RegisterGenerateOptionRp) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.name, rhs.name) && deepEqualsMessages(lhs.id, rhs.id)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RegisterGenerateOptionRp")
    deepHashMessages(value: name, hasher: &hasher)
    deepHashMessages(value: id, hasher: &hasher)
  }
}

/// Represents user information for registration
///
/// Generated class from Pigeon that represents data sent in messages.
struct RegisterGenerateOptionUser: Hashable {
  /// User identifier
  var id: String
  /// User name
  var name: String
  /// Display name (defaults to empty string)
  var displayName: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegisterGenerateOptionUser? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let displayName = pigeonVar_list[2] as! String

    return RegisterGenerateOptionUser(
      id: id,
      name: name,
      displayName: displayName
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      displayName,
    ]
  }
  static func == (lhs: RegisterGenerateOptionUser, rhs: RegisterGenerateOptionUser) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.id, rhs.id) && deepEqualsMessages(lhs.name, rhs.name) && deepEqualsMessages(lhs.displayName, rhs.displayName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RegisterGenerateOptionUser")
    deepHashMessages(value: id, hasher: &hasher)
    deepHashMessages(value: name, hasher: &hasher)
    deepHashMessages(value: displayName, hasher: &hasher)
  }
}

/// Represents public key credential parameters
///
/// Generated class from Pigeon that represents data sent in messages.
struct RegisterGenerateOptionPublicKeyParams: Hashable {
  /// Algorithm identifier
  var alg: Int64
  /// Credential type
  var type: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegisterGenerateOptionPublicKeyParams? {
    let alg = pigeonVar_list[0] as! Int64
    let type = pigeonVar_list[1] as! String

    return RegisterGenerateOptionPublicKeyParams(
      alg: alg,
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      alg,
      type,
    ]
  }
  static func == (lhs: RegisterGenerateOptionPublicKeyParams, rhs: RegisterGenerateOptionPublicKeyParams) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.alg, rhs.alg) && deepEqualsMessages(lhs.type, rhs.type)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RegisterGenerateOptionPublicKeyParams")
    deepHashMessages(value: alg, hasher: &hasher)
    deepHashMessages(value: type, hasher: &hasher)
  }
}

/// Represents authenticator selection criteria
///
/// Generated class from Pigeon that represents data sent in messages.
struct RegisterGenerateOptionAuthenticatorSelection: Hashable {
  /// Resident key requirement
  var residentKey: String
  /// User verification requirement
  var userVerification: String
  /// Whether resident key is required
  var requireResidentKey: Bool
  /// Authenticator attachment preference
  var authenticatorAttachment: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegisterGenerateOptionAuthenticatorSelection? {
    let residentKey = pigeonVar_list[0] as! String
    let userVerification = pigeonVar_list[1] as! String
    let requireResidentKey = pigeonVar_list[2] as! Bool
    let authenticatorAttachment = pigeonVar_list[3] as! String

    return RegisterGenerateOptionAuthenticatorSelection(
      residentKey: residentKey,
      userVerification: userVerification,
      requireResidentKey: requireResidentKey,
      authenticatorAttachment: authenticatorAttachment
    )
  }
  func toList() -> [Any?] {
    return [
      residentKey,
      userVerification,
      requireResidentKey,
      authenticatorAttachment,
    ]
  }
  static func == (lhs: RegisterGenerateOptionAuthenticatorSelection, rhs: RegisterGenerateOptionAuthenticatorSelection) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.residentKey, rhs.residentKey) && deepEqualsMessages(lhs.userVerification, rhs.userVerification) && deepEqualsMessages(lhs.requireResidentKey, rhs.requireResidentKey) && deepEqualsMessages(lhs.authenticatorAttachment, rhs.authenticatorAttachment)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RegisterGenerateOptionAuthenticatorSelection")
    deepHashMessages(value: residentKey, hasher: &hasher)
    deepHashMessages(value: userVerification, hasher: &hasher)
    deepHashMessages(value: requireResidentKey, hasher: &hasher)
    deepHashMessages(value: authenticatorAttachment, hasher: &hasher)
  }
}

/// Represents extensions for registration
///
/// Generated class from Pigeon that represents data sent in messages.
struct RegisterGenerateOptionExtension: Hashable {
  /// Credential properties extension
  var credProps: Bool
  /// PRF extension input parameters
  var prf: PrfExtensionInput? = nil
  /// LargeBlob extension input for registration
  var largeBlob: LargeBlobExtensionRegistrationInput? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegisterGenerateOptionExtension? {
    let credProps = pigeonVar_list[0] as! Bool
    let prf: PrfExtensionInput? = nilOrValue(pigeonVar_list[1])
    let largeBlob: LargeBlobExtensionRegistrationInput? = nilOrValue(pigeonVar_list[2])

    return RegisterGenerateOptionExtension(
      credProps: credProps,
      prf: prf,
      largeBlob: largeBlob
    )
  }
  func toList() -> [Any?] {
    return [
      credProps,
      prf,
      largeBlob,
    ]
  }
  static func == (lhs: RegisterGenerateOptionExtension, rhs: RegisterGenerateOptionExtension) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.credProps, rhs.credProps) && deepEqualsMessages(lhs.prf, rhs.prf) && deepEqualsMessages(lhs.largeBlob, rhs.largeBlob)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RegisterGenerateOptionExtension")
    deepHashMessages(value: credProps, hasher: &hasher)
    deepHashMessages(value: prf, hasher: &hasher)
    deepHashMessages(value: largeBlob, hasher: &hasher)
  }
}

/// Represents the response data for registration verification
///
/// Generated class from Pigeon that represents data sent in messages.
struct RegisterVerifyResponse: Hashable {
  /// Whether the registration was verified
  var verified: Bool
  /// Access token for authenticated session
  var accessToken: String
  /// User information
  var user: User
  /// Refresh token for session renewal
  var refreshToken: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegisterVerifyResponse? {
    let verified = pigeonVar_list[0] as! Bool
    let accessToken = pigeonVar_list[1] as! String
    let user = pigeonVar_list[2] as! User
    let refreshToken = pigeonVar_list[3] as! String

    return RegisterVerifyResponse(
      verified: verified,
      accessToken: accessToken,
      user: user,
      refreshToken: refreshToken
    )
  }
  func toList() -> [Any?] {
    return [
      verified,
      accessToken,
      user,
      refreshToken,
    ]
  }
  static func == (lhs: RegisterVerifyResponse, rhs: RegisterVerifyResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.verified, rhs.verified) && deepEqualsMessages(lhs.accessToken, rhs.accessToken) && deepEqualsMessages(lhs.user, rhs.user) && deepEqualsMessages(lhs.refreshToken, rhs.refreshToken)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RegisterVerifyResponse")
    deepHashMessages(value: verified, hasher: &hasher)
    deepHashMessages(value: accessToken, hasher: &hasher)
    deepHashMessages(value: user, hasher: &hasher)
    deepHashMessages(value: refreshToken, hasher: &hasher)
  }
}

/// WebAuthn PRF Extension Input payload
/// The WebAuthn specification stipulates eval dictionaries contain `first` (and optionally `second`)
/// salt strings. The underlying platform APIs (like Android Credential Manager) expect these Strings
/// to be Base64URL-encoded representations of a 32-byte ArrayBuffer.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PrfExtensionInput: Hashable {
  /// The dictionary structure containing salts ('first' and optionally 'second')
  var eval: [String?: String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PrfExtensionInput? {
    let eval: [String?: String?]? = nilOrValue(pigeonVar_list[0])

    return PrfExtensionInput(
      eval: eval
    )
  }
  func toList() -> [Any?] {
    return [
      eval
    ]
  }
  static func == (lhs: PrfExtensionInput, rhs: PrfExtensionInput) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.eval, rhs.eval)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PrfExtensionInput")
    deepHashMessages(value: eval, hasher: &hasher)
  }
}

/// Represents PRF extension output results
///
/// Generated class from Pigeon that represents data sent in messages.
struct PrfExtensionOutput: Hashable {
  /// Whether PRF is enabled for this credential
  var enabled: Bool? = nil
  /// The dictionary structure containing derived salts ('first' and optionally 'second')
  var results: [String?: String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PrfExtensionOutput? {
    let enabled: Bool? = nilOrValue(pigeonVar_list[0])
    let results: [String?: String?]? = nilOrValue(pigeonVar_list[1])

    return PrfExtensionOutput(
      enabled: enabled,
      results: results
    )
  }
  func toList() -> [Any?] {
    return [
      enabled,
      results,
    ]
  }
  static func == (lhs: PrfExtensionOutput, rhs: PrfExtensionOutput) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.enabled, rhs.enabled) && deepEqualsMessages(lhs.results, rhs.results)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PrfExtensionOutput")
    deepHashMessages(value: enabled, hasher: &hasher)
    deepHashMessages(value: results, hasher: &hasher)
  }
}

/// LargeBlob extension input for registration
/// Indicates whether the authenticator should support largeBlob storage
///
/// Generated class from Pigeon that represents data sent in messages.
struct LargeBlobExtensionRegistrationInput: Hashable {
  /// Support preference: "preferred" or "required"
  var support: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LargeBlobExtensionRegistrationInput? {
    let support: String? = nilOrValue(pigeonVar_list[0])

    return LargeBlobExtensionRegistrationInput(
      support: support
    )
  }
  func toList() -> [Any?] {
    return [
      support
    ]
  }
  static func == (lhs: LargeBlobExtensionRegistrationInput, rhs: LargeBlobExtensionRegistrationInput) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.support, rhs.support)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LargeBlobExtensionRegistrationInput")
    deepHashMessages(value: support, hasher: &hasher)
  }
}

/// LargeBlob extension output for registration
/// Indicates whether the authenticator supports largeBlob storage
///
/// Generated class from Pigeon that represents data sent in messages.
struct LargeBlobExtensionRegistrationOutput: Hashable {
  /// Whether the authenticator supports largeBlob
  var supported: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LargeBlobExtensionRegistrationOutput? {
    let supported: Bool? = nilOrValue(pigeonVar_list[0])

    return LargeBlobExtensionRegistrationOutput(
      supported: supported
    )
  }
  func toList() -> [Any?] {
    return [
      supported
    ]
  }
  static func == (lhs: LargeBlobExtensionRegistrationOutput, rhs: LargeBlobExtensionRegistrationOutput) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.supported, rhs.supported)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LargeBlobExtensionRegistrationOutput")
    deepHashMessages(value: supported, hasher: &hasher)
  }
}

/// LargeBlob extension input for authentication
/// Supports reading or writing blob data (mutually exclusive per WebAuthn spec)
///
/// Generated class from Pigeon that represents data sent in messages.
struct LargeBlobExtensionAuthInput: Hashable {
  /// Set to true to read the stored blob
  var read: Bool? = nil
  /// Data to write to the blob
  var write: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LargeBlobExtensionAuthInput? {
    let read: Bool? = nilOrValue(pigeonVar_list[0])
    let write: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])

    return LargeBlobExtensionAuthInput(
      read: read,
      write: write
    )
  }
  func toList() -> [Any?] {
    return [
      read,
      write,
    ]
  }
  static func == (lhs: LargeBlobExtensionAuthInput, rhs: LargeBlobExtensionAuthInput) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.read, rhs.read) && deepEqualsMessages(lhs.write, rhs.write)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LargeBlobExtensionAuthInput")
    deepHashMessages(value: read, hasher: &hasher)
    deepHashMessages(value: write, hasher: &hasher)
  }
}

/// LargeBlob extension output for authentication
/// Contains the read blob data or write success status
///
/// Generated class from Pigeon that represents data sent in messages.
struct LargeBlobExtensionAuthOutput: Hashable {
  /// The retrieved blob data (when read was requested)
  var blob: FlutterStandardTypedData? = nil
  /// Whether the write operation succeeded (when write was requested)
  var written: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LargeBlobExtensionAuthOutput? {
    let blob: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[0])
    let written: Bool? = nilOrValue(pigeonVar_list[1])

    return LargeBlobExtensionAuthOutput(
      blob: blob,
      written: written
    )
  }
  func toList() -> [Any?] {
    return [
      blob,
      written,
    ]
  }
  static func == (lhs: LargeBlobExtensionAuthOutput, rhs: LargeBlobExtensionAuthOutput) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.blob, rhs.blob) && deepEqualsMessages(lhs.written, rhs.written)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LargeBlobExtensionAuthOutput")
    deepHashMessages(value: blob, hasher: &hasher)
    deepHashMessages(value: written, hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PasskeyErrorType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return PasskeyException.fromList(self.readValue() as! [Any?])
    case 131:
      return AuthGenerateOptionResponseData.fromList(self.readValue() as! [Any?])
    case 132:
      return AuthGenerateOptionExtension.fromList(self.readValue() as! [Any?])
    case 133:
      return AuthGenerateOptionAllowCredential.fromList(self.readValue() as! [Any?])
    case 134:
      return AuthVerifyResponse.fromList(self.readValue() as! [Any?])
    case 135:
      return User.fromList(self.readValue() as! [Any?])
    case 136:
      return CreatePasskeyResponseData.fromList(self.readValue() as! [Any?])
    case 137:
      return CreatePasskeyResponse.fromList(self.readValue() as! [Any?])
    case 138:
      return CreatePasskeyExtension.fromList(self.readValue() as! [Any?])
    case 139:
      return CreatePasskeyExtensionProps.fromList(self.readValue() as! [Any?])
    case 140:
      return GetPasskeyAuthenticationResponseData.fromList(self.readValue() as! [Any?])
    case 141:
      return AuthPasskeyExtensionResult.fromList(self.readValue() as! [Any?])
    case 142:
      return GetPasskeyAuthenticationResponse.fromList(self.readValue() as! [Any?])
    case 143:
      return RegisterGenerateOptionData.fromList(self.readValue() as! [Any?])
    case 144:
      return RegisterGenerateOptionExcludeCredential.fromList(self.readValue() as! [Any?])
    case 145:
      return RegisterGenerateOptionRp.fromList(self.readValue() as! [Any?])
    case 146:
      return RegisterGenerateOptionUser.fromList(self.readValue() as! [Any?])
    case 147:
      return RegisterGenerateOptionPublicKeyParams.fromList(self.readValue() as! [Any?])
    case 148:
      return RegisterGenerateOptionAuthenticatorSelection.fromList(self.readValue() as! [Any?])
    case 149:
      return RegisterGenerateOptionExtension.fromList(self.readValue() as! [Any?])
    case 150:
      return RegisterVerifyResponse.fromList(self.readValue() as! [Any?])
    case 151:
      return PrfExtensionInput.fromList(self.readValue() as! [Any?])
    case 152:
      return PrfExtensionOutput.fromList(self.readValue() as! [Any?])
    case 153:
      return LargeBlobExtensionRegistrationInput.fromList(self.readValue() as! [Any?])
    case 154:
      return LargeBlobExtensionRegistrationOutput.fromList(self.readValue() as! [Any?])
    case 155:
      return LargeBlobExtensionAuthInput.fromList(self.readValue() as! [Any?])
    case 156:
      return LargeBlobExtensionAuthOutput.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PasskeyErrorType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PasskeyException {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? AuthGenerateOptionResponseData {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? AuthGenerateOptionExtension {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? AuthGenerateOptionAllowCredential {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? AuthVerifyResponse {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? User {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? CreatePasskeyResponseData {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? CreatePasskeyResponse {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? CreatePasskeyExtension {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? CreatePasskeyExtensionProps {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? GetPasskeyAuthenticationResponseData {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? AuthPasskeyExtensionResult {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? GetPasskeyAuthenticationResponse {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? RegisterGenerateOptionData {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? RegisterGenerateOptionExcludeCredential {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? RegisterGenerateOptionRp {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? RegisterGenerateOptionUser {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? RegisterGenerateOptionPublicKeyParams {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? RegisterGenerateOptionAuthenticatorSelection {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? RegisterGenerateOptionExtension {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? RegisterVerifyResponse {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? PrfExtensionInput {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? PrfExtensionOutput {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? LargeBlobExtensionRegistrationInput {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? LargeBlobExtensionRegistrationOutput {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else if let value = value as? LargeBlobExtensionAuthInput {
      super.writeByte(155)
      super.writeValue(value.toList())
    } else if let value = value as? LargeBlobExtensionAuthOutput {
      super.writeByte(156)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Host API for passkey operations from Flutter to native platforms
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PasskeyHostApi {
  /// Registers a new passkey credential
  func register(options: RegisterGenerateOptionData, completion: @escaping (Result<CreatePasskeyResponseData, Error>) -> Void)
  /// Authenticates with an existing passkey
  func authenticate(request: AuthGenerateOptionResponseData, completion: @escaping (Result<GetPasskeyAuthenticationResponseData, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PasskeyHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `PasskeyHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PasskeyHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Registers a new passkey credential
    let registerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_passkey_service.PasskeyHostApi.register\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! RegisterGenerateOptionData
        api.register(options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerChannel.setMessageHandler(nil)
    }
    /// Authenticates with an existing passkey
    let authenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_passkey_service.PasskeyHostApi.authenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! AuthGenerateOptionResponseData
        api.authenticate(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateChannel.setMessageHandler(nil)
    }
  }
}
