package com.example.flutter_passkey_service

import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.embedding.engine.plugins.activity.ActivityAware
import io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding
import android.app.Activity

/** FlutterPasskeyServicePlugin */
class FlutterPasskeyServicePlugin : FlutterPlugin, ActivityAware {
    private var activity: Activity? = null
    private var passkeyHostApi: PasskeyHostApiImpl? = null

    override fun onAttachedToEngine(flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
        // Set up the Pigeon-generated API
        passkeyHostApi = PasskeyHostApiImpl(flutterPluginBinding.applicationContext)
        
        // Register the API with Pigeon (this method will be generated by Pigeon)
        PasskeyHostApi.setUp(flutterPluginBinding.binaryMessenger, passkeyHostApi)
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        // Clean up the API
        PasskeyHostApi.setUp(binding.binaryMessenger, null)
        passkeyHostApi = null
    }

    // ActivityAware implementation to get access to the current activity
    override fun onAttachedToActivity(binding: ActivityPluginBinding) {
        activity = binding.activity
        passkeyHostApi?.setActivity(activity)
    }

    override fun onDetachedFromActivityForConfigChanges() {
        activity = null
        passkeyHostApi?.setActivity(null)
    }

    override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) {
        activity = binding.activity
        passkeyHostApi?.setActivity(activity)
    }

    override fun onDetachedFromActivity() {
        activity = null
        passkeyHostApi?.setActivity(null)
    }
}
