// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.flutter_passkey_service

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Predefined error types for consistent error handling across platforms */
enum class PasskeyErrorType(val raw: Int) {
  INVALID_PARAMETERS(0),
  MISSING_REQUIRED_FIELD(1),
  INVALID_FORMAT(2),
  DECODING_CHALLENGE(3),
  USER_CANCELLED(4),
  USER_TIMEOUT(5),
  USER_OPTED_OUT(6),
  INSUFFICIENT_PERMISSIONS(7),
  SECURITY_VIOLATION(8),
  NOT_ALLOWED(9),
  DOMAIN_NOT_ASSOCIATED(10),
  NO_CREDENTIALS_AVAILABLE(11),
  CREDENTIAL_NOT_FOUND(12),
  INVALID_CREDENTIAL(13),
  CREDENTIAL_ALREADY_EXISTS(14),
  INVALID_RESPONSE(15),
  NOT_HANDLED(16),
  FAILED(17),
  PLATFORM_NOT_SUPPORTED(18),
  OPERATION_NOT_SUPPORTED(19),
  SYSTEM_ERROR(20),
  NETWORK_ERROR(21),
  DOM_ERROR(22),
  WEBAUTHN_ERROR(23),
  ATTESTATION_ERROR(24),
  EXCLUDE_CREDENTIALS_MATCH(25),
  UNEXPECTED_AUTHORIZATION_RESPONSE(26),
  WK_ERROR_DOMAIN(27),
  UNKNOWN_ERROR(28),
  UNEXPECTED_ERROR(29);

  companion object {
    fun ofRaw(raw: Int): PasskeyErrorType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Represents a standardized passkey exception that can be thrown across platforms
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PasskeyException (
  /** Error type identifying the specific type of error */
  val errorType: PasskeyErrorType,
  /** Error message describing what went wrong */
  val message: String,
  /** Optional additional details about the error */
  val details: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PasskeyException {
      val errorType = pigeonVar_list[0] as PasskeyErrorType
      val message = pigeonVar_list[1] as String
      val details = pigeonVar_list[2] as String
      return PasskeyException(errorType, message, details)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      errorType,
      message,
      details,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PasskeyException
    return MessagesPigeonUtils.deepEquals(this.errorType, other.errorType) && MessagesPigeonUtils.deepEquals(this.message, other.message) && MessagesPigeonUtils.deepEquals(this.details, other.details)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.details)
    return result
  }
}

/**
 * Represents the response data for authentication generation options
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AuthGenerateOptionResponseData (
  /** The relying party identifier */
  val rpId: String,
  /** The challenge string */
  val challenge: String,
  /** List of allowed credentials */
  val allowCredentials: List<AuthGenerateOptionAllowCredential>,
  /** Timeout value in milliseconds */
  val timeout: Long,
  /** User verification requirement */
  val userVerification: String,
  /** Hints for the authenticator */
  val hints: List<String?>? = null,
  /** Extensions for authentication */
  val extensions: AuthGenerateOptionExtension? = null,
  /** Prefer credentials immediately available on-device (no QR/remote prompts) */
  val preferImmediatelyAvailableCredentials: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthGenerateOptionResponseData {
      val rpId = pigeonVar_list[0] as String
      val challenge = pigeonVar_list[1] as String
      val allowCredentials = pigeonVar_list[2] as List<AuthGenerateOptionAllowCredential>
      val timeout = pigeonVar_list[3] as Long
      val userVerification = pigeonVar_list[4] as String
      val hints = pigeonVar_list[5] as List<String?>?
      val extensions = pigeonVar_list[6] as AuthGenerateOptionExtension?
      val preferImmediatelyAvailableCredentials = pigeonVar_list[7] as Boolean?
      return AuthGenerateOptionResponseData(rpId, challenge, allowCredentials, timeout, userVerification, hints, extensions, preferImmediatelyAvailableCredentials)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rpId,
      challenge,
      allowCredentials,
      timeout,
      userVerification,
      hints,
      extensions,
      preferImmediatelyAvailableCredentials,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AuthGenerateOptionResponseData
    return MessagesPigeonUtils.deepEquals(this.rpId, other.rpId) && MessagesPigeonUtils.deepEquals(this.challenge, other.challenge) && MessagesPigeonUtils.deepEquals(this.allowCredentials, other.allowCredentials) && MessagesPigeonUtils.deepEquals(this.timeout, other.timeout) && MessagesPigeonUtils.deepEquals(this.userVerification, other.userVerification) && MessagesPigeonUtils.deepEquals(this.hints, other.hints) && MessagesPigeonUtils.deepEquals(this.extensions, other.extensions) && MessagesPigeonUtils.deepEquals(this.preferImmediatelyAvailableCredentials, other.preferImmediatelyAvailableCredentials)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rpId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.challenge)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.allowCredentials)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timeout)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.userVerification)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hints)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.extensions)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.preferImmediatelyAvailableCredentials)
    return result
  }
}

/**
 * Represents extensions for authentication options
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AuthGenerateOptionExtension (
  /** AppID extension */
  val appid: Boolean? = null,
  /** PRF extension input parameters */
  val prf: PrfExtensionInput? = null,
  /** LargeBlob extension input for authentication */
  val largeBlob: LargeBlobExtensionAuthInput? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthGenerateOptionExtension {
      val appid = pigeonVar_list[0] as Boolean?
      val prf = pigeonVar_list[1] as PrfExtensionInput?
      val largeBlob = pigeonVar_list[2] as LargeBlobExtensionAuthInput?
      return AuthGenerateOptionExtension(appid, prf, largeBlob)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      appid,
      prf,
      largeBlob,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AuthGenerateOptionExtension
    return MessagesPigeonUtils.deepEquals(this.appid, other.appid) && MessagesPigeonUtils.deepEquals(this.prf, other.prf) && MessagesPigeonUtils.deepEquals(this.largeBlob, other.largeBlob)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.appid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.prf)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.largeBlob)
    return result
  }
}

/**
 * Represents an allowed credential for authentication
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AuthGenerateOptionAllowCredential (
  /** The credential identifier */
  val id: String,
  /** The credential type */
  val type: String,
  /** List of transport methods */
  val transports: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthGenerateOptionAllowCredential {
      val id = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as String
      val transports = pigeonVar_list[2] as List<String>
      return AuthGenerateOptionAllowCredential(id, type, transports)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      type,
      transports,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AuthGenerateOptionAllowCredential
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.transports, other.transports)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.transports)
    return result
  }
}

/**
 * Represents the response data for authentication verification
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AuthVerifyResponse (
  /** Whether the authentication was verified */
  val verified: Boolean,
  /** Access token for authenticated session */
  val accessToken: String,
  /** User information (optional) */
  val user: User? = null,
  /** Refresh token for session renewal */
  val refreshToken: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthVerifyResponse {
      val verified = pigeonVar_list[0] as Boolean
      val accessToken = pigeonVar_list[1] as String
      val user = pigeonVar_list[2] as User?
      val refreshToken = pigeonVar_list[3] as String
      return AuthVerifyResponse(verified, accessToken, user, refreshToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      verified,
      accessToken,
      user,
      refreshToken,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AuthVerifyResponse
    return MessagesPigeonUtils.deepEquals(this.verified, other.verified) && MessagesPigeonUtils.deepEquals(this.accessToken, other.accessToken) && MessagesPigeonUtils.deepEquals(this.user, other.user) && MessagesPigeonUtils.deepEquals(this.refreshToken, other.refreshToken)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.verified)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.accessToken)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.user)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.refreshToken)
    return result
  }
}

/**
 * Represents user information
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class User (
  /** User identifier */
  val id: String,
  /** Username */
  val username: String,
  /** Phone number (optional) */
  val phone: String? = null,
  /** Email address (optional) */
  val email: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): User {
      val id = pigeonVar_list[0] as String
      val username = pigeonVar_list[1] as String
      val phone = pigeonVar_list[2] as String?
      val email = pigeonVar_list[3] as String?
      return User(id, username, phone, email)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      username,
      phone,
      email,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as User
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.username, other.username) && MessagesPigeonUtils.deepEquals(this.phone, other.phone) && MessagesPigeonUtils.deepEquals(this.email, other.email)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.username)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.phone)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.email)
    return result
  }
}

/**
 * Represents the response data for creating a passkey
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CreatePasskeyResponseData (
  /** Raw identifier */
  val rawId: String,
  /** Authenticator attachment type */
  val authenticatorAttachment: String? = null,
  /** Type of credential */
  val type: String,
  /** Credential identifier */
  val id: String,
  /** Response data from passkey creation */
  val response: CreatePasskeyResponse,
  /** Client extension results */
  val clientExtensionResults: CreatePasskeyExtension,
  /** Username associated with the passkey */
  val username: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreatePasskeyResponseData {
      val rawId = pigeonVar_list[0] as String
      val authenticatorAttachment = pigeonVar_list[1] as String?
      val type = pigeonVar_list[2] as String
      val id = pigeonVar_list[3] as String
      val response = pigeonVar_list[4] as CreatePasskeyResponse
      val clientExtensionResults = pigeonVar_list[5] as CreatePasskeyExtension
      val username = pigeonVar_list[6] as String
      return CreatePasskeyResponseData(rawId, authenticatorAttachment, type, id, response, clientExtensionResults, username)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rawId,
      authenticatorAttachment,
      type,
      id,
      response,
      clientExtensionResults,
      username,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CreatePasskeyResponseData
    return MessagesPigeonUtils.deepEquals(this.rawId, other.rawId) && MessagesPigeonUtils.deepEquals(this.authenticatorAttachment, other.authenticatorAttachment) && MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.response, other.response) && MessagesPigeonUtils.deepEquals(this.clientExtensionResults, other.clientExtensionResults) && MessagesPigeonUtils.deepEquals(this.username, other.username)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rawId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authenticatorAttachment)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.response)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clientExtensionResults)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.username)
    return result
  }
}

/**
 * Represents the response from passkey creation
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CreatePasskeyResponse (
  /** Client data JSON */
  val clientDataJSON: String,
  /** Attestation object */
  val attestationObject: String,
  /** List of transport methods */
  val transports: List<String?>? = null,
  /** Authenticator data */
  val authenticatorData: String? = null,
  /** Public key algorithm identifier */
  val publicKeyAlgorithm: Long? = null,
  /** Public key */
  val publicKey: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreatePasskeyResponse {
      val clientDataJSON = pigeonVar_list[0] as String
      val attestationObject = pigeonVar_list[1] as String
      val transports = pigeonVar_list[2] as List<String?>?
      val authenticatorData = pigeonVar_list[3] as String?
      val publicKeyAlgorithm = pigeonVar_list[4] as Long?
      val publicKey = pigeonVar_list[5] as String?
      return CreatePasskeyResponse(clientDataJSON, attestationObject, transports, authenticatorData, publicKeyAlgorithm, publicKey)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      clientDataJSON,
      attestationObject,
      transports,
      authenticatorData,
      publicKeyAlgorithm,
      publicKey,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CreatePasskeyResponse
    return MessagesPigeonUtils.deepEquals(this.clientDataJSON, other.clientDataJSON) && MessagesPigeonUtils.deepEquals(this.attestationObject, other.attestationObject) && MessagesPigeonUtils.deepEquals(this.transports, other.transports) && MessagesPigeonUtils.deepEquals(this.authenticatorData, other.authenticatorData) && MessagesPigeonUtils.deepEquals(this.publicKeyAlgorithm, other.publicKeyAlgorithm) && MessagesPigeonUtils.deepEquals(this.publicKey, other.publicKey)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clientDataJSON)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.attestationObject)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.transports)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authenticatorData)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.publicKeyAlgorithm)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.publicKey)
    return result
  }
}

/**
 * Represents client extension results for passkey creation
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CreatePasskeyExtension (
  /** Credential properties extension (optional) */
  val credProps: CreatePasskeyExtensionProps? = null,
  /** PRF extension (optional) */
  val prf: PrfExtensionOutput? = null,
  /** LargeBlob extension output for registration */
  val largeBlob: LargeBlobExtensionRegistrationOutput? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreatePasskeyExtension {
      val credProps = pigeonVar_list[0] as CreatePasskeyExtensionProps?
      val prf = pigeonVar_list[1] as PrfExtensionOutput?
      val largeBlob = pigeonVar_list[2] as LargeBlobExtensionRegistrationOutput?
      return CreatePasskeyExtension(credProps, prf, largeBlob)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      credProps,
      prf,
      largeBlob,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CreatePasskeyExtension
    return MessagesPigeonUtils.deepEquals(this.credProps, other.credProps) && MessagesPigeonUtils.deepEquals(this.prf, other.prf) && MessagesPigeonUtils.deepEquals(this.largeBlob, other.largeBlob)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.credProps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.prf)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.largeBlob)
    return result
  }
}

/**
 * Represents credential properties extension
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CreatePasskeyExtensionProps (
  /** Resident key flag */
  val rk: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreatePasskeyExtensionProps {
      val rk = pigeonVar_list[0] as Boolean
      return CreatePasskeyExtensionProps(rk)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rk,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CreatePasskeyExtensionProps
    return MessagesPigeonUtils.deepEquals(this.rk, other.rk)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rk)
    return result
  }
}

/**
 * Represents the response data for passkey authentication
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class GetPasskeyAuthenticationResponseData (
  /** Authenticator attachment type */
  val authenticatorAttachment: String? = null,
  /** Credential identifier */
  val id: String,
  /** Raw identifier */
  val rawId: String,
  /** Authentication response data */
  val response: GetPasskeyAuthenticationResponse,
  /** Type of credential */
  val type: String,
  /** Client extension results */
  val clientExtensionResults: AuthPasskeyExtensionResult? = null,
  /** Username associated with the passkey */
  val username: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetPasskeyAuthenticationResponseData {
      val authenticatorAttachment = pigeonVar_list[0] as String?
      val id = pigeonVar_list[1] as String
      val rawId = pigeonVar_list[2] as String
      val response = pigeonVar_list[3] as GetPasskeyAuthenticationResponse
      val type = pigeonVar_list[4] as String
      val clientExtensionResults = pigeonVar_list[5] as AuthPasskeyExtensionResult?
      val username = pigeonVar_list[6] as String
      return GetPasskeyAuthenticationResponseData(authenticatorAttachment, id, rawId, response, type, clientExtensionResults, username)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      authenticatorAttachment,
      id,
      rawId,
      response,
      type,
      clientExtensionResults,
      username,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GetPasskeyAuthenticationResponseData
    return MessagesPigeonUtils.deepEquals(this.authenticatorAttachment, other.authenticatorAttachment) && MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.rawId, other.rawId) && MessagesPigeonUtils.deepEquals(this.response, other.response) && MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.clientExtensionResults, other.clientExtensionResults) && MessagesPigeonUtils.deepEquals(this.username, other.username)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authenticatorAttachment)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rawId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.response)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clientExtensionResults)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.username)
    return result
  }
}

/**
 * Represents client extension results for passkey authentication
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AuthPasskeyExtensionResult (
  /** AppID extension result */
  val appid: Boolean? = null,
  /** PRF extension output results */
  val prf: PrfExtensionOutput? = null,
  /** LargeBlob extension output for authentication */
  val largeBlob: LargeBlobExtensionAuthOutput? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthPasskeyExtensionResult {
      val appid = pigeonVar_list[0] as Boolean?
      val prf = pigeonVar_list[1] as PrfExtensionOutput?
      val largeBlob = pigeonVar_list[2] as LargeBlobExtensionAuthOutput?
      return AuthPasskeyExtensionResult(appid, prf, largeBlob)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      appid,
      prf,
      largeBlob,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AuthPasskeyExtensionResult
    return MessagesPigeonUtils.deepEquals(this.appid, other.appid) && MessagesPigeonUtils.deepEquals(this.prf, other.prf) && MessagesPigeonUtils.deepEquals(this.largeBlob, other.largeBlob)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.appid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.prf)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.largeBlob)
    return result
  }
}

/**
 * Represents the authentication response from passkey
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class GetPasskeyAuthenticationResponse (
  /** Client data JSON */
  val clientDataJSON: String,
  /** Authenticator data */
  val authenticatorData: String,
  /** Digital signature */
  val signature: String,
  /** User handle (optional) */
  val userHandle: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetPasskeyAuthenticationResponse {
      val clientDataJSON = pigeonVar_list[0] as String
      val authenticatorData = pigeonVar_list[1] as String
      val signature = pigeonVar_list[2] as String
      val userHandle = pigeonVar_list[3] as String?
      return GetPasskeyAuthenticationResponse(clientDataJSON, authenticatorData, signature, userHandle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      clientDataJSON,
      authenticatorData,
      signature,
      userHandle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GetPasskeyAuthenticationResponse
    return MessagesPigeonUtils.deepEquals(this.clientDataJSON, other.clientDataJSON) && MessagesPigeonUtils.deepEquals(this.authenticatorData, other.authenticatorData) && MessagesPigeonUtils.deepEquals(this.signature, other.signature) && MessagesPigeonUtils.deepEquals(this.userHandle, other.userHandle)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clientDataJSON)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authenticatorData)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.signature)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.userHandle)
    return result
  }
}

/**
 * Represents the data for generating registration options
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RegisterGenerateOptionData (
  /** Challenge string */
  val challenge: String,
  /** Relying party information */
  val rp: RegisterGenerateOptionRp,
  /** User information */
  val user: RegisterGenerateOptionUser,
  /** Public key credential parameters */
  val pubKeyCredParams: List<RegisterGenerateOptionPublicKeyParams>,
  /** Timeout value in milliseconds */
  val timeout: Long,
  /** Attestation preference */
  val attestation: String,
  /** Credentials to exclude from registration */
  val excludeCredentials: List<RegisterGenerateOptionExcludeCredential>,
  /** Authenticator selection criteria */
  val authenticatorSelection: RegisterGenerateOptionAuthenticatorSelection,
  /** Extensions for registration */
  val extensions: RegisterGenerateOptionExtension,
  /** Hints for the authenticator */
  val hints: List<String?>? = null,
  /** Attestation formats */
  val attestationFormats: List<String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RegisterGenerateOptionData {
      val challenge = pigeonVar_list[0] as String
      val rp = pigeonVar_list[1] as RegisterGenerateOptionRp
      val user = pigeonVar_list[2] as RegisterGenerateOptionUser
      val pubKeyCredParams = pigeonVar_list[3] as List<RegisterGenerateOptionPublicKeyParams>
      val timeout = pigeonVar_list[4] as Long
      val attestation = pigeonVar_list[5] as String
      val excludeCredentials = pigeonVar_list[6] as List<RegisterGenerateOptionExcludeCredential>
      val authenticatorSelection = pigeonVar_list[7] as RegisterGenerateOptionAuthenticatorSelection
      val extensions = pigeonVar_list[8] as RegisterGenerateOptionExtension
      val hints = pigeonVar_list[9] as List<String?>?
      val attestationFormats = pigeonVar_list[10] as List<String?>?
      return RegisterGenerateOptionData(challenge, rp, user, pubKeyCredParams, timeout, attestation, excludeCredentials, authenticatorSelection, extensions, hints, attestationFormats)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      challenge,
      rp,
      user,
      pubKeyCredParams,
      timeout,
      attestation,
      excludeCredentials,
      authenticatorSelection,
      extensions,
      hints,
      attestationFormats,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RegisterGenerateOptionData
    return MessagesPigeonUtils.deepEquals(this.challenge, other.challenge) && MessagesPigeonUtils.deepEquals(this.rp, other.rp) && MessagesPigeonUtils.deepEquals(this.user, other.user) && MessagesPigeonUtils.deepEquals(this.pubKeyCredParams, other.pubKeyCredParams) && MessagesPigeonUtils.deepEquals(this.timeout, other.timeout) && MessagesPigeonUtils.deepEquals(this.attestation, other.attestation) && MessagesPigeonUtils.deepEquals(this.excludeCredentials, other.excludeCredentials) && MessagesPigeonUtils.deepEquals(this.authenticatorSelection, other.authenticatorSelection) && MessagesPigeonUtils.deepEquals(this.extensions, other.extensions) && MessagesPigeonUtils.deepEquals(this.hints, other.hints) && MessagesPigeonUtils.deepEquals(this.attestationFormats, other.attestationFormats)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.challenge)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rp)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.user)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.pubKeyCredParams)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timeout)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.attestation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.excludeCredentials)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authenticatorSelection)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.extensions)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hints)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.attestationFormats)
    return result
  }
}

/**
 * Represents a credential to exclude from registration
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RegisterGenerateOptionExcludeCredential (
  /** Credential identifier */
  val id: String,
  /** Credential type */
  val type: String,
  /** List of transport methods */
  val transports: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RegisterGenerateOptionExcludeCredential {
      val id = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as String
      val transports = pigeonVar_list[2] as List<String>
      return RegisterGenerateOptionExcludeCredential(id, type, transports)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      type,
      transports,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RegisterGenerateOptionExcludeCredential
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.transports, other.transports)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.transports)
    return result
  }
}

/**
 * Represents relying party information for registration
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RegisterGenerateOptionRp (
  /** Relying party name */
  val name: String,
  /** Relying party identifier */
  val id: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RegisterGenerateOptionRp {
      val name = pigeonVar_list[0] as String
      val id = pigeonVar_list[1] as String
      return RegisterGenerateOptionRp(name, id)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      id,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RegisterGenerateOptionRp
    return MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.id, other.id)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    return result
  }
}

/**
 * Represents user information for registration
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RegisterGenerateOptionUser (
  /** User identifier */
  val id: String,
  /** User name */
  val name: String,
  /** Display name (defaults to empty string) */
  val displayName: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RegisterGenerateOptionUser {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val displayName = pigeonVar_list[2] as String
      return RegisterGenerateOptionUser(id, name, displayName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      displayName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RegisterGenerateOptionUser
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.displayName, other.displayName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.displayName)
    return result
  }
}

/**
 * Represents public key credential parameters
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RegisterGenerateOptionPublicKeyParams (
  /** Algorithm identifier */
  val alg: Long,
  /** Credential type */
  val type: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RegisterGenerateOptionPublicKeyParams {
      val alg = pigeonVar_list[0] as Long
      val type = pigeonVar_list[1] as String
      return RegisterGenerateOptionPublicKeyParams(alg, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      alg,
      type,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RegisterGenerateOptionPublicKeyParams
    return MessagesPigeonUtils.deepEquals(this.alg, other.alg) && MessagesPigeonUtils.deepEquals(this.type, other.type)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.alg)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    return result
  }
}

/**
 * Represents authenticator selection criteria
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RegisterGenerateOptionAuthenticatorSelection (
  /** Resident key requirement */
  val residentKey: String,
  /** User verification requirement */
  val userVerification: String,
  /** Whether resident key is required */
  val requireResidentKey: Boolean,
  /** Authenticator attachment preference */
  val authenticatorAttachment: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RegisterGenerateOptionAuthenticatorSelection {
      val residentKey = pigeonVar_list[0] as String
      val userVerification = pigeonVar_list[1] as String
      val requireResidentKey = pigeonVar_list[2] as Boolean
      val authenticatorAttachment = pigeonVar_list[3] as String
      return RegisterGenerateOptionAuthenticatorSelection(residentKey, userVerification, requireResidentKey, authenticatorAttachment)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      residentKey,
      userVerification,
      requireResidentKey,
      authenticatorAttachment,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RegisterGenerateOptionAuthenticatorSelection
    return MessagesPigeonUtils.deepEquals(this.residentKey, other.residentKey) && MessagesPigeonUtils.deepEquals(this.userVerification, other.userVerification) && MessagesPigeonUtils.deepEquals(this.requireResidentKey, other.requireResidentKey) && MessagesPigeonUtils.deepEquals(this.authenticatorAttachment, other.authenticatorAttachment)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.residentKey)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.userVerification)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.requireResidentKey)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authenticatorAttachment)
    return result
  }
}

/**
 * Represents extensions for registration
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RegisterGenerateOptionExtension (
  /** Credential properties extension */
  val credProps: Boolean,
  /** PRF extension input parameters */
  val prf: PrfExtensionInput? = null,
  /** LargeBlob extension input for registration */
  val largeBlob: LargeBlobExtensionRegistrationInput? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RegisterGenerateOptionExtension {
      val credProps = pigeonVar_list[0] as Boolean
      val prf = pigeonVar_list[1] as PrfExtensionInput?
      val largeBlob = pigeonVar_list[2] as LargeBlobExtensionRegistrationInput?
      return RegisterGenerateOptionExtension(credProps, prf, largeBlob)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      credProps,
      prf,
      largeBlob,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RegisterGenerateOptionExtension
    return MessagesPigeonUtils.deepEquals(this.credProps, other.credProps) && MessagesPigeonUtils.deepEquals(this.prf, other.prf) && MessagesPigeonUtils.deepEquals(this.largeBlob, other.largeBlob)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.credProps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.prf)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.largeBlob)
    return result
  }
}

/**
 * Represents the response data for registration verification
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RegisterVerifyResponse (
  /** Whether the registration was verified */
  val verified: Boolean,
  /** Access token for authenticated session */
  val accessToken: String,
  /** User information */
  val user: User,
  /** Refresh token for session renewal */
  val refreshToken: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RegisterVerifyResponse {
      val verified = pigeonVar_list[0] as Boolean
      val accessToken = pigeonVar_list[1] as String
      val user = pigeonVar_list[2] as User
      val refreshToken = pigeonVar_list[3] as String
      return RegisterVerifyResponse(verified, accessToken, user, refreshToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      verified,
      accessToken,
      user,
      refreshToken,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RegisterVerifyResponse
    return MessagesPigeonUtils.deepEquals(this.verified, other.verified) && MessagesPigeonUtils.deepEquals(this.accessToken, other.accessToken) && MessagesPigeonUtils.deepEquals(this.user, other.user) && MessagesPigeonUtils.deepEquals(this.refreshToken, other.refreshToken)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.verified)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.accessToken)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.user)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.refreshToken)
    return result
  }
}

/**
 * WebAuthn PRF Extension Input payload
 * The WebAuthn specification stipulates eval dictionaries contain `first` (and optionally `second`)
 * salt strings. The underlying platform APIs (like Android Credential Manager) expect these Strings
 * to be Base64URL-encoded representations of a 32-byte ArrayBuffer.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PrfExtensionInput (
  /** The dictionary structure containing salts ('first' and optionally 'second') */
  val eval: Map<String?, String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PrfExtensionInput {
      val eval = pigeonVar_list[0] as Map<String?, String?>?
      return PrfExtensionInput(eval)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      eval,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PrfExtensionInput
    return MessagesPigeonUtils.deepEquals(this.eval, other.eval)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.eval)
    return result
  }
}

/**
 * Represents PRF extension output results
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PrfExtensionOutput (
  /** Whether PRF is enabled for this credential */
  val enabled: Boolean? = null,
  /** The dictionary structure containing derived salts ('first' and optionally 'second') */
  val results: Map<String?, String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PrfExtensionOutput {
      val enabled = pigeonVar_list[0] as Boolean?
      val results = pigeonVar_list[1] as Map<String?, String?>?
      return PrfExtensionOutput(enabled, results)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      enabled,
      results,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PrfExtensionOutput
    return MessagesPigeonUtils.deepEquals(this.enabled, other.enabled) && MessagesPigeonUtils.deepEquals(this.results, other.results)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enabled)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.results)
    return result
  }
}

/**
 * LargeBlob extension input for registration
 * Indicates whether the authenticator should support largeBlob storage
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LargeBlobExtensionRegistrationInput (
  /** Support preference: "preferred" or "required" */
  val support: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LargeBlobExtensionRegistrationInput {
      val support = pigeonVar_list[0] as String?
      return LargeBlobExtensionRegistrationInput(support)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      support,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LargeBlobExtensionRegistrationInput
    return MessagesPigeonUtils.deepEquals(this.support, other.support)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.support)
    return result
  }
}

/**
 * LargeBlob extension output for registration
 * Indicates whether the authenticator supports largeBlob storage
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LargeBlobExtensionRegistrationOutput (
  /** Whether the authenticator supports largeBlob */
  val supported: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LargeBlobExtensionRegistrationOutput {
      val supported = pigeonVar_list[0] as Boolean?
      return LargeBlobExtensionRegistrationOutput(supported)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      supported,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LargeBlobExtensionRegistrationOutput
    return MessagesPigeonUtils.deepEquals(this.supported, other.supported)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.supported)
    return result
  }
}

/**
 * LargeBlob extension input for authentication
 * Supports reading or writing blob data (mutually exclusive per WebAuthn spec)
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LargeBlobExtensionAuthInput (
  /** Set to true to read the stored blob */
  val read: Boolean? = null,
  /** Data to write to the blob */
  val write: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LargeBlobExtensionAuthInput {
      val read = pigeonVar_list[0] as Boolean?
      val write = pigeonVar_list[1] as ByteArray?
      return LargeBlobExtensionAuthInput(read, write)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      read,
      write,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LargeBlobExtensionAuthInput
    return MessagesPigeonUtils.deepEquals(this.read, other.read) && MessagesPigeonUtils.deepEquals(this.write, other.write)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.read)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.write)
    return result
  }
}

/**
 * LargeBlob extension output for authentication
 * Contains the read blob data or write success status
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LargeBlobExtensionAuthOutput (
  /** The retrieved blob data (when read was requested) */
  val blob: ByteArray? = null,
  /** Whether the write operation succeeded (when write was requested) */
  val written: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LargeBlobExtensionAuthOutput {
      val blob = pigeonVar_list[0] as ByteArray?
      val written = pigeonVar_list[1] as Boolean?
      return LargeBlobExtensionAuthOutput(blob, written)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      blob,
      written,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LargeBlobExtensionAuthOutput
    return MessagesPigeonUtils.deepEquals(this.blob, other.blob) && MessagesPigeonUtils.deepEquals(this.written, other.written)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.blob)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.written)
    return result
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PasskeyErrorType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PasskeyException.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuthGenerateOptionResponseData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuthGenerateOptionExtension.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuthGenerateOptionAllowCredential.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuthVerifyResponse.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          User.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreatePasskeyResponseData.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreatePasskeyResponse.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreatePasskeyExtension.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreatePasskeyExtensionProps.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GetPasskeyAuthenticationResponseData.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuthPasskeyExtensionResult.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GetPasskeyAuthenticationResponse.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegisterGenerateOptionData.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegisterGenerateOptionExcludeCredential.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegisterGenerateOptionRp.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegisterGenerateOptionUser.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegisterGenerateOptionPublicKeyParams.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegisterGenerateOptionAuthenticatorSelection.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegisterGenerateOptionExtension.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegisterVerifyResponse.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PrfExtensionInput.fromList(it)
        }
      }
      152.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PrfExtensionOutput.fromList(it)
        }
      }
      153.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LargeBlobExtensionRegistrationInput.fromList(it)
        }
      }
      154.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LargeBlobExtensionRegistrationOutput.fromList(it)
        }
      }
      155.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LargeBlobExtensionAuthInput.fromList(it)
        }
      }
      156.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LargeBlobExtensionAuthOutput.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PasskeyErrorType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PasskeyException -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is AuthGenerateOptionResponseData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AuthGenerateOptionExtension -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is AuthGenerateOptionAllowCredential -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is AuthVerifyResponse -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is User -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is CreatePasskeyResponseData -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is CreatePasskeyResponse -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is CreatePasskeyExtension -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is CreatePasskeyExtensionProps -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is GetPasskeyAuthenticationResponseData -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is AuthPasskeyExtensionResult -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is GetPasskeyAuthenticationResponse -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is RegisterGenerateOptionData -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is RegisterGenerateOptionExcludeCredential -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is RegisterGenerateOptionRp -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is RegisterGenerateOptionUser -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is RegisterGenerateOptionPublicKeyParams -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is RegisterGenerateOptionAuthenticatorSelection -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is RegisterGenerateOptionExtension -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is RegisterVerifyResponse -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is PrfExtensionInput -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      is PrfExtensionOutput -> {
        stream.write(152)
        writeValue(stream, value.toList())
      }
      is LargeBlobExtensionRegistrationInput -> {
        stream.write(153)
        writeValue(stream, value.toList())
      }
      is LargeBlobExtensionRegistrationOutput -> {
        stream.write(154)
        writeValue(stream, value.toList())
      }
      is LargeBlobExtensionAuthInput -> {
        stream.write(155)
        writeValue(stream, value.toList())
      }
      is LargeBlobExtensionAuthOutput -> {
        stream.write(156)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API for passkey operations from Flutter to native platforms
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface PasskeyHostApi {
  /** Registers a new passkey credential */
  fun register(options: RegisterGenerateOptionData, callback: (Result<CreatePasskeyResponseData>) -> Unit)
  /** Authenticates with an existing passkey */
  fun authenticate(request: AuthGenerateOptionResponseData, callback: (Result<GetPasskeyAuthenticationResponseData>) -> Unit)

  companion object {
    /** The codec used by PasskeyHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `PasskeyHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PasskeyHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_passkey_service.PasskeyHostApi.register$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as RegisterGenerateOptionData
            api.register(optionsArg) { result: Result<CreatePasskeyResponseData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_passkey_service.PasskeyHostApi.authenticate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as AuthGenerateOptionResponseData
            api.authenticate(requestArg) { result: Result<GetPasskeyAuthenticationResponseData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
