name: 🐛 Bug Report
description: Report a bug or issue with Flutter Passkey Service
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the following information to help us resolve your issue quickly.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check all the boxes below before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I have read the documentation and followed the setup instructions
          required: true
        - label: I am using a supported platform (iOS 16.0+ or Android API 28+)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to...
        2. Call method...
        3. Expected result...
        4. Actual result...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: dart
      placeholder: |
        // Minimal code sample
        try {
          final options = FlutterPasskeyService.createRegistrationOptions(/*...*/);
          final result = await FlutterPasskeyService.register(options);
        } catch (e) {
          print('Error: $e');
        }
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please provide any relevant error logs or stack traces
      render: text
      placeholder: Paste error logs here...
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you experiencing this issue on?
      options:
        - iOS
        - Android
        - Both iOS and Android
    validations:
      required: true

  - type: input
    id: flutter_version
    attributes:
      label: Flutter Version
      description: Output of `flutter --version`
      placeholder: "Flutter 3.24.0 • channel stable"
    validations:
      required: true

  - type: input
    id: plugin_version
    attributes:
      label: Plugin Version
      description: Which version of flutter_passkey_service are you using?
      placeholder: "0.0.3"
    validations:
      required: true

  - type: input
    id: ios_version
    attributes:
      label: iOS Version (if applicable)
      description: iOS version if the issue is on iOS
      placeholder: "iOS 17.0"
    validations:
      required: false

  - type: input
    id: android_version
    attributes:
      label: Android Version (if applicable)
      description: Android version and API level if the issue is on Android
      placeholder: "Android 14 (API 34)"
    validations:
      required: false

  - type: input
    id: device
    attributes:
      label: Device Model
      description: Device model where the issue occurs
      placeholder: "iPhone 15 Pro, Pixel 8, etc."
    validations:
      required: false

  - type: checkboxes
    id: domain_setup
    attributes:
      label: Domain Setup
      description: Domain verification setup (check all that apply)
      options:
        - label: I have set up Apple App Site Association file
        - label: I have set up Android Digital Asset Links file
        - label: Domain verification is working correctly
        - label: Using localhost/development setup

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help...
    validations:
      required: false
