name: ✨ Feature Request
description: Suggest a new feature or enhancement for Flutter Passkey Service
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! We appreciate your input and want to understand your use case.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check all the boxes below before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested already
          required: true
        - label: I have read the documentation to confirm this feature doesn't already exist
          required: true
        - label: This feature request is related to Flutter Passkey Service functionality
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: "As a developer, I need... because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work? Describe your ideal solution.
      placeholder: "I would like the plugin to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions or workarounds have you considered?
      placeholder: "I considered using... but..."
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Provide an example of how you would use this feature in code
      render: dart
      placeholder: |
        // Example of how this feature would be used
        final result = await FlutterPasskeyService.newFeature(
          parameter: 'value',
        );
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be useful
        - High - Important for my use case
        - Critical - Blocking my project
    validations:
      required: true

  - type: checkboxes
    id: platforms
    attributes:
      label: Target Platforms
      description: Which platforms should this feature support?
      options:
        - label: iOS
        - label: Android
        - label: Web (future consideration)

  - type: checkboxes
    id: type
    attributes:
      label: Feature Type
      description: What type of feature is this? (check all that apply)
      options:
        - label: New API method
        - label: Enhancement to existing functionality
        - label: Performance improvement
        - label: Developer experience improvement
        - label: Security enhancement
        - label: Platform-specific feature
        - label: Documentation improvement

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: Any additional information that helps explain the feature...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help with documentation
